data:
    dataset: "RainDrop"
    image_size: 64 # Raindrop_DiT, RDiffusion, onego
    channels: 3
    num_workers: 24
    data_dir: "/data1/Deraining_Dataset/DayRainDrop_Train/"
    data_val_dir: "/data1/Deraining_Dataset/DayRainDrop_Test/"
    conditional: True

model:
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 1, 2, 2, 4, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    patch_n: 4
    batch_size: 16
    n_epochs: 37042
    n_iters: 2000000
    snapshot_freq: 5000
    validation_freq: 1000000

sampling:
    batch_size: 1
    last_only: True

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.0001
    amsgrad: False
    eps: 0.00000001
